// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAU1oiTBfrzV3Dgxz9sHSBCJGVnkA1LaAE',
    appId: '1:339599564623:web:c333b8714508114c292f3a',
    messagingSenderId: '339599564623',
    projectId: 'rounoteflutter',
    authDomain: 'rounoteflutter.firebaseapp.com',
    storageBucket: 'rounoteflutter.appspot.com',
    measurementId: 'G-7G55YHRPCF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3frRHAuNKoNRDNf0P6jS_1E3WgxMSGAo',
    appId: '1:339599564623:android:9870250ecc6e4ae1292f3a',
    messagingSenderId: '339599564623',
    projectId: 'rounoteflutter',
    storageBucket: 'rounoteflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6Tn2xVuqAeLLACWJbKH5wfvcc6H2nWig',
    appId: '1:339599564623:ios:b5e35d9225bc6a2c292f3a',
    messagingSenderId: '339599564623',
    projectId: 'rounoteflutter',
    storageBucket: 'rounoteflutter.appspot.com',
    iosClientId: '339599564623-n7qldrfmipsovc595pn5eetok6n4o4n6.apps.googleusercontent.com',
    iosBundleId: 'tech.routechnology.rounoteflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6Tn2xVuqAeLLACWJbKH5wfvcc6H2nWig',
    appId: '1:339599564623:ios:b5e35d9225bc6a2c292f3a',
    messagingSenderId: '339599564623',
    projectId: 'rounoteflutter',
    storageBucket: 'rounoteflutter.appspot.com',
    iosClientId: '339599564623-n7qldrfmipsovc595pn5eetok6n4o4n6.apps.googleusercontent.com',
    iosBundleId: 'tech.routechnology.rounoteflutter',
  );
}
